= Minekube

== Minikube work

https://kubernetes.io/docs/setup/learning-environment/minikube/


.Set default driver to kvm2
[source,bash]
----
minikube config set driver kvm2
----

.We need to set the environment variables with
[source,bash]
----
eval $(minikube docker-env)
----

.We can unset the environment variables with this command
[source,bash]
----
eval $(minikube docker-env -u)
----

To be make it possible to deploy from "local" registry are we starting `Minikub` with the option `--insecure-registry`.

[source,bash]
----
minikube start \
    -p micbn \
	--cpus 4 \
	--memory 16384 \
	--disk-size 10g \
	--vm-driver=kvm2 \
	--insecure-registry "192.168.1.0/24"
----

[source,bash]
----
minikube start \
    -p micbn \
    --driver=podman \
    --insecure-registry "192.168.1.0/24"
----

[source,bash]
----
minikube stop -p micbn
----

[source,bash]
----
minikube delete -p micbn
----

[source,bash]
----
minikube dashboard --url -p micbn
minikube service jaegertracing --url -p micbn
minikube service pgadmin --url -p micbn
minikube service postgresqldemo --url -p micbn
minikube service prometheus --url -p micbn
----

== Registry

.Enable registry on Minecube
[source,bash]
----
minikube addons enable registry -p micbn
----

.port-forward to registry - available on localhost:5000
[source,bash]
----
kubectl port-forward --namespace kube-system service/registry 5000:80
----

.Get ip of registry
[source,bash]
----
kubectl get services --namespace=kube-system
----

.Test connection to registry
[source,bash]
----
curl http://localhost:5000/v2/_catalog
----

== Istio

.Install Istio into Minekube
[source,bash]
----
istioctl install
----

.See progress of Install Istio into Minekube
[source,bash]
----
kubectl -n istio-system get deploy
----

.Inspect the installed-state CR
[source,bash]
----
kubectl -n istio-system get IstioOperator installed-state -o yaml > installed-istio-state.yaml
----

https://istio.io/

== Deployments

=== PostgreSQL

Deploy postgres:14.5

link:postgres/README.adoc[postgres/README.adoc]

=== pgAdmin

Deploy dpage/pgadmin4:5

link:pgadmin/README.adoc[pgadmin/README.adoc]

=== Jaeger

Deploy jaegertracing/all-in-one:1.37

link:jaegertracing/README.adoc[jaegertracing/README.adoc]

=== Prometheus

Deploy prom/prometheus:v2.38.0

link:prometheus/README.adoc[prometheus/README.adoc]

== Commands

https://minikube.sigs.k8s.io/docs/commands/[Minikube commands]

[source,bash]
----
minikube dashboard
----

[source,bash]
----
minikube service list
----

[source,bash]
----
minikube service jaegertracing --url
----

== Minekube Documentation

https://minikube.sigs.k8s.io/docs/

https://minikube.sigs.k8s.io/docs/handbook/controls/[Basic controls]


=== Minikube temp registry

We will use a `temp` registry runing on ip 192.168.1.36 - matching `--insecure-registry "192.168.1.0/24"` from when we started `minikube`.

[source,bash]
----
podman run -it -p 5000:5000 --name registry registry:2
----

[source,bash]
----
podman build -f src/main/docker/Dockerfile.native -t quarkus/native/todo-app .
podman push 192.168.1.36:5000/quarkus/native/todo-app
----

[source,bash]
----
echo '' >> /etc/containers/registries.conf
echo '# Manual update' >> /etc/containers/registries.conf
echo '[[registry]]' >> /etc/containers/registries.conf
echo 'prefix = "192.168.1.36:5000"' >> /etc/containers/registries.conf
echo 'location = "192.168.1.36:5000/quarkus"' >> /etc/containers/registries.conf
echo 'insecure = true' >> /etc/containers/registries.conf
----


== Kubernetes Documentation

https://kubernetes.io/docs/home/


https://kubernetes.io/docs/tasks/access-application-cluster/list-all-running-container-images/[List all Container images in all namespaces]

[source,bash]
----
kubectl get pods --all-namespaces -o jsonpath="{..image}" |\
tr -s '[[:space:]]' '\n' |\
sort |\
uniq -c
----


== Volumes

Using podman for minikube we have some rescrition.

- we can't use `hostPath` in `PersistentVolume`
- we can't use `local` in `PersistentVolume`

https://kubernetes.io/docs/concepts/storage/persistent-volumes/[Persistent Volumes | Kubernetes]

=== Setup nsf

Following https://mikebarkas.dev/2019/setup-nfs-for-minikube-persistent-storage/[Setup NFS For Minikube] can be a help.

I stoped just before `Client Configuration` and is using `nfs` in configuration of volumes.

== Links

- https://minikube.sigs.k8s.io/docs/handbook/registry/