apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  labels:
    app: pgadmin
data:
  PGADMIN_DEFAULT_EMAIL: pgadmin@jarry.dk
  PGADMIN_DEFAULT_PASSWORD: mysecretpassword
  PGADMIN_CONFIG_LOGIN_BANNER : Authorised users only!