kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgadmin-pv-claim
  labels:
    app: pgadmin
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi