apiVersion: v1
kind: Service
metadata:
  name: kafka-server-ingress-nginx
  labels:
    app.kubernetes.io/name: kafka-server-ingress-nginx
spec:
  type: LoadBalancer
  ports:
    - name: plaintest
      port: 9092
      targetPort: 9092
      protocol: TCP
    - name: ssl
      port: 9093
      targetPort: 9093
      protocol: TCP
  selector:
    app.kubernetes.io/name: kafka-server-broker1 