apiVersion: v1
kind: Service
metadata:
  name: kafka-server-service-broker3
  labels:
    app.kubernetes.io/name: kafka-server-service-broker3
spec:
  ports:
    - port: 9092
      name: plantext
    - port: 9093
      name: ssl
  selector:
    app.kubernetes.io/name: kafka-server-broker3