apiVersion: v1
kind: Pod
metadata:
  name: kafka-server-broker1
  labels:
    environment: development
    app.kubernetes.io/name: kafka-server-broker1
spec:
  containers:
    - name: kafka-server-broker1
      image: docker.io/jarrydk/fedora-minimal-kafka:3.5.0-v2
      imagePullPolicy: "IfNotPresent"
      ports:
        - containerPort: 9092
        - containerPort: 9093
      envFrom:
        - configMapRef:
            name: kafka-server-config
      env:
        - name: "KAFKA_LISTENERS"
          value: "PLAINTEXT://:9092,SSL://:9093,INTERNAL_PLAINTEXT://:9094"
        - name: "KAFKA_LISTENER_SECURITY_PROTOCAL_MAP"
          value: "PLAINTEXT:PLAINTEXT,INTERNAL_PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL"
        - name: "KAFKA_INTER_BROKER_LISTENER_NAME"
          value: "INTERNAL_PLAINTEXT"
        - name: "KAFKA_ADVERTISED_LISTENERS"
          value: "PLAINTEXT://broker1.jarry.dk:9092,SSL://broker1.jarry.dk:9093,INTERNAL_PLAINTEXT://:9094"
        - name: "KAFKA_SSL_TRUSTSTORE_LOCATION"
          value: "/var/kafka/certs/kafka.server.truststore.jks"
        - name: "KAFKA_SSL_TRUSTSTORE_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: kafka-server-secret
              key: kafka-server-truststore-password
        - name: "KAFKA_SSL_KEYSTORE_LOCATION"
          value: "/var/kafka/certs/broker1.jarry.dk.keystore.jks"
        - name: "KAFKA_SSL_KEYSTORE_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: kafka-server-secret
              key: kafka-server-keystore-password
        - name: "KAFKA_SSL_CLIENT_AUTH"
          value: "requested"
        - name: "KAFKA_BROKER_ID"
          value: "1"
        - name: "KAFKA_LOG_DIRS"
          value: "/var/kafka/data"
      volumeMounts:
        - name: secret-volume
          mountPath: "/var/kafka/certs"
        - name: kafka-server-data
          mountPath: "/var/kafka/data"
  volumes:
    - name: secret-volume
      secret:
        secretName: kafka-server-secret
    - name: kafka-server-data
      persistentVolumeClaim:
        claimName: kafka-server-broker1-pv-claim