apiVersion: v1
kind: Service
metadata:
  name: kafka-zookeeper
  labels:
    app.kubernetes.io/name: kafka-zookeeper
spec:
  # type: NodePort
  ports:
    - port: 2181
  selector:
    app.kubernetes.io/name: kafka-zookeeper