apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-without-sni
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: demo.example.com
      http:
        paths:
          - path:
            backend:
              serviceName: kafka-server-service-broker1
              servicePort: 9092
          - path:
            backend:
              serviceName: kafka-server-service-broker2
              servicePort: 9092
          - path:
            backend:
              serviceName: kafka-server-service-broker3
              servicePort: 9092