kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kafka-server-broker2-pv-claim
  labels:
    app.kubernetes.io/name: kafka-server
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi