apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-server-pv-broker3
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/default/kafka-server-pv-broker3