apiVersion: v1
kind: Service
metadata:
  name: kafka-server-broker3
  labels:
    app.kubernetes.io/name: kafka-server-service-broker3
spec:
  # type: LoadBalancer
  ports:
    - name: plantext
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: ssl
      protocol: TCP
      port: 9093
      targetPort: 9093
  selector:
    app.kubernetes.io/name: kafka-server-broker3