= Minekube - Kafka

== Create PersistentVolume / PersistentVolumeClaim

NOTE: Naming in this sektion is bad !

[source.bash]
----
minikube ssh
sudo mkdir -p /mnt/data/default/kafka-server-pv-broker1
sudo mkdir -p /mnt/data/default/kafka-server-pv-broker2
sudo mkdir -p /mnt/data/default/kafka-server-pv-broker3
----

=== PersistentVolume

.kafka-server-pv-broker1.yaml
[source.yaml]
----
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-server-pv-broker1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/default/kafka-server-pv-broker1
----

[source.bash]
----
kubectl apply -f kafka-server-pv-broker1.yaml
----

=== PersistentVolumeClaim

.kafka-server-pv-broker1.yaml
[source.yaml]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kafka-server-broker1-pv-claim
  labels:
    app.kubernetes.io/name: kafka-server
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
----

[source.bash]
----
kubectl apply -f kafka-server-pv-broker1.yaml
----

=== Links

- https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/[Configure a Pod to Use a PersistentVolume for Storage]
- https://kubernetes.io/docs/concepts/storage/persistent-volumes/[Persistent Volumes]

== Create secret

[source.bash]
----
kubectl create secret generic kafka-server-secret \
	--from-file=/opt/apache/kafka/jarry_dk/broker1.jarry.dk.keystore.jks \
	--from-file=/opt/apache/kafka/jarry_dk/broker2.jarry.dk.keystore.jks \
	--from-file=/opt/apache/kafka/jarry_dk/broker3.jarry.dk.keystore.jks \
	--from-file=/opt/apache/kafka/jarry_dk/kafka.client.truststore.jks \
	--from-file=/opt/apache/kafka/jarry_dk/kafka.server.truststore.jks \
	--from-literal=kafka-server-keystore-password=password1234 \
	--from-literal=kafka-server-truststore-password=password1234
----

The output of the command can be seen in link:kafka-server-secret.yaml[kafka-server-secret.yaml]

== LoadBalancer on minikube


=== Tunnel

By default you can't use `LoadBalancer` on `minikube`, but `tunnel` is you friend.

[source.bash]
----
minikube tunnel
----

=== port-forward

[source.bash]
----
kubectl port-forward --address 127.0.2.21 service/kafka-server-broker1 9092:9092
kubectl port-forward --address 127.0.2.21 service/kafka-server-broker1 9093:9093
kubectl port-forward --address 127.0.2.22 service/kafka-server-broker2 9092:9092
kubectl port-forward --address 127.0.2.22 service/kafka-server-broker2 9092:9092
kubectl port-forward --address 127.0.2.23 service/kafka-server-broker3 9092:9092
kubectl port-forward --address 127.0.2.23 service/kafka-server-broker3 9092:9092
----

=== Testing

.Create topic
[source.bash]
----
$KAFKA_HOME/bin/kafka-topics.sh \
    --bootstrap-server broker1.jarry.dk:9092 \
    --topic kafka-mod-entity-event \
    --create
----

.Describe topic
[source.bash]
----
$KAFKA_HOME/bin/kafka-topics.sh \
    --bootstrap-server broker1.jarry.dk:9092 \
    --topic kafka-mod-entity-event \
    --describe
----

.Consume form topic
[source.bash]
----
$KAFKA_HOME/bin/kafka-console-consumer.sh \
    --bootstrap-server broker1.jarry.dk:9092 \
    --topic kafka-mod-entity-even \
    --from-beginning | jq
----



== Ingress

https://docs.confluent.io/operator/current/co-staticportbased.html

== Debug

.nicolaka/netshoot
[source.bash]
----
kubectl run tmp-shell --rm -i --tty --overrides='{"spec": {"hostNetwork": true}}'  --image nicolaka/netshoot
----

.dnsutils
[source.bash]
----
kubectl apply -f https://k8s.io/examples/admin/dns/dnsutils.yaml
kubectl exec -i -t dnsutils -- nslookup kafka-zookeeper
----

== Links

- https://strimzi.io/[Strimzi provides a way to run an Apache Kafka cluster on Kubernetes in various deployment configurations.]
- https://github.com/banzaicloud/koperator[Koperator is an open-source operator that automates the provisioning, management, and autoscaling of Apache Kafka clusters on Kubernetes]
- https://learnk8s.io/kafka-ha-kubernetes[Designing and testing a highly available Kafka cluster on Kubernetes]
- https://bitnami.com/stack/kafka/helm[Apache Kafka packaged by Bitnami]