apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaegertracing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaegertracing
  template:
    metadata:
      labels:
        app: jaegertracing
    spec:
      containers:
        - name: jaegertracing
          image: jaegertracing/all-in-one:1.37
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5775
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 5778
            - containerPort: 16686
            - containerPort: 14268
---
apiVersion: v1
kind: Service
metadata:
  name: jaegertracing
  labels:
    app: jaegertracing
spec:
  type: NodePort
  ports:
   - protocol: UDP
     port: 5775
     targetPort: 5775
     name: udp-5775
   - protocol: UDP
     port: 6831
     targetPort: 6831
     name: udp-6831
   - protocol: UDP
     port: 6832
     targetPort: 6832
     name: udp-6832
   - protocol: TCP
     port: 5778
     targetPort: 5778
     name: tcp-5778
   - protocol: TCP
     port: 16686
     targetPort: 16686
     name: tcp-16686
   - protocol: TCP
     port: 14268
     targetPort: 14268
     name: tcp-14268
  selector:
   app: jaegertracing
